### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by shankiesan** [rubenarakelyan/twfyapi#3]
This is really great work, @rubenarakelyan – but could I suggest one small improvement, that is in error handling? Currently, errors internal to your class are handled using die(), whereas errors coming back from the TWFY services are returned as `array('error'=>'Invalid postcode')`. 

When die is used, it's hard to capture and process them sensibly. I'd like to suggest handling them in a similar way to TWFY and returning an array with the element `error`.

I'll fork the project and make the changes and issue a pull request. Let me know if you think it's sensible...

**Comment by rubenarakelyan** [comment]
Thanks very much for your work on this and sorry for the massive delay in getting it merged in!

**Comment by shankiesan** [comment]
That's alright, my pleasure! I'm the one that should thank you for the
original SDK – it helped get my project off the ground.
